merge v16, extract .desktop Name/Comment
This does not yet merge the translations back into .desktop however.

We also remove the --package-version argument as it was adding an
extra space after the package name even though the version was empty.

We also set the CHARSET=UTF-8 in the pot file.

diff --git a/package/translate/merge b/package/translate/merge
--- a/package/translate/merge
+++ b/package/translate/merge
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Version: 15
+# Version: 16
 
 # https://techbase.kde.org/Development/Tutorials/Localization/i18n_Build_Systems
 # Based on: https://github.com/psifidotos/nowdock-plasmoid/blob/master/po/Messages.sh
@@ -27,20 +27,32 @@ fi
 
 #---
 echo "[merge] Extracting messages"
-find "${packageRoot}" -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.qml' -o -name '*.js' | sort > "${DIR}/infiles.list"
+potArgs="--from-code=UTF-8 --width=200 --add-location=file"
 
+find "${packageRoot}" -name '*.desktop' | sort > "${DIR}/infiles.list"
 xgettext \
-	--from-code=UTF-8 \
+	${potArgs} \
+	--files-from="${DIR}/infiles.list" \
+	--language=Desktop \
+	-D "${packageRoot}" \
+	-D "${DIR}" \
+	-o "template.pot.new" \
+	|| \
+	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
+
+sed -i 's/"Content-Type: text\/plain; charset=CHARSET\\n"/"Content-Type: text\/plain; charset=UTF-8\\n"/' "template.pot.new"
+
+find "${packageRoot}" -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.qml' -o -name '*.js' | sort > "${DIR}/infiles.list"
+xgettext \
+	${potArgs} \
+	--files-from="${DIR}/infiles.list" \
 	-C -kde -ci18n -ki18n:1 -ki18nc:1c,2 -ki18np:1,2 -ki18ncp:1c,2,3 -ktr2i18n:1 -kI18N_NOOP:1 \
 	-kI18N_NOOP2:1c,2  -kN_:1 -kaliasLocale -kki18n:1 -kki18nc:1c,2 -kki18np:1,2 -kki18ncp:1c,2,3 \
-	--files-from="infiles.list" \
-	--width=200 \
-	--add-location=file \
 	--package-name="${widgetName}" \
-	--package-version="" \
 	--msgid-bugs-address="${bugAddress}" \
 	-D "${packageRoot}" \
 	-D "${DIR}" \
+	--join-existing \
 	-o "template.pot.new" \
 	|| \
 	{ echo "[merge] error while calling xgettext. aborting."; exit 1; }
